### ISSUE TITLE
Errore mail uscita in cool-jconon

### ISSUE THREAD

**Issue by regacr** [consiglionazionaledellericerche/cool-jconon#1]
Buongiorno,
stiamo testando all'interno del nostro ente l'applicazione cool-jconon per la gestione delle candidature del personale on-line.
L'installazione è andata a buon fine, ma abbiamo dei problemi riguardanti l'invio delle mail in uscita, nello specifico l'invio della mail di conferma di avvenuta registrazione di un nuovo utente.

Posto qui sotto i log riguardanti l'errore e la configurazione per il nostro server smtp inserita nel file alfresco-properties all'interno del path **~/cool-jconon/docker-compose**

`jconon_1         |      at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
jconon_1         |      at java.lang.Thread.run(Thread.java:745)
jconon_1         | Caused by: org.springframework.mail.MailSendException: Failed messages: javax.mail.SendFailedException: Invalid Addresses;
jconon_1         |   nested exception is:
jconon_1         |      com.sun.mail.smtp.SMTPAddressFailedException: 554 5.7.1 <c.reghelin@lacasaschio.it>: Relay access denied
jconon_1         | ;
jconon_1         |   nested exception is:
jconon_1         |      com.sun.mail.smtp.SMTPAddressFailedException: 554 5.7.1 <jconon.test@cnr.it>: Recipient address rejected: Access denied
jconon_1         |
jconon_1         |      at org.springframework.mail.javamail.JavaMailSenderImpl.doSend(JavaMailSenderImpl.java:490)
jconon_1         |      at org.springframework.mail.javamail.JavaMailSenderImpl.send(JavaMailSenderImpl.java:360)
jconon_1         |      at org.springframework.mail.javamail.JavaMailSenderImpl.send(JavaMailSenderImpl.java:377)
jconon_1         |      at org.springframework.mail.javamail.JavaMailSenderImpl.send(JavaMailSenderImpl.java:365)
jconon_1         |      at it.cnr.cool.mail.MailServiceImpl.send(MailServiceImpl.java:218)
jconon_1         |      ... 72 common frames omitted`

SMTP settings:
`mail.host=192.XXX.XXX.XXX
mail.port=25
mail.username=anonymous
mail.password=
mail.encoding=UTF-8
mail.header=
mail.from.default=info@xxxxxx.it
mail.protocol=smtp
mail.smtp.auth=false`

Grazie in anticipo per l'aiuto

**Comment by mspasiano** [comment]
Salve,
Le configurazioni per le mail in uscita vanno inserite in jconon e non in alfresco.
La configurazione possono essere customizzate tramite le variabili d'ambiente oppure passandole come parametro nel command java con il -D ad esempio:

jconon:
    image: consiglionazionalericerche/cool-jconon:latest
    read_only: false
    environment:
      - JAVA_OPTS="-Xmx1g"
      - LANG=it_IT.UTF-8
      - ORG_APACHE_CHEMISTRY_OPENCMIS_BINDING_CONNECTTIMEOUT=120000
      - REPOSITORY_BASE_URL=http://my-alfresco:8080/alfresco/
      - SPID_ENABLE=true
      - SERVER_SERVLET_CONTEXT_PATH=/
      - SPID_ISSUER_ENTITYID=https://miauri.it
      - MAIL_HOST=192.XXX.XXX.XXX
      - MAIL_FROM_DEFAULT=info@xxxxxx.it
    volumes:
      - ./jconon_logs:/logs
      - /tmp
    command: java -Xmx512m -Xss512k -Djava.security.egd=file:/dev/./urandom -jar /opt/jconon.war
    labels:
      - SERVICE_NAME=cool-jconon
    depends_on:
      - alfresco
    links:
      - alfresco:my-alfresco

**Comment by mspasiano** [comment]
Ciao @regacr posso considerare la issue risolta?

**Comment by regacr** [comment]
Problema risolto.

Grazie
