### ISSUE TITLE
Repeated Luogo field in modifying Reperibilità by RdP

### ISSUE THREAD

**Issue by duiliol** [consiglionazionaledellericerche/cool-jconon#22]
![image](https://user-images.githubusercontent.com/34539337/141303124-f39b8350-8045-4d53-b091-94502982cae9.png)

Luogo appears twice, and in the first occurrence it also requires provincia as mandatory, that cannot be inserted if the place is foreign. Regardless of this mandatory request, modification is possible and happens correctly.

**Comment by mspasiano** [comment]
Closed on version 4.9.29
