### ISSUE TITLE
[4.10.2] - State for exclusions and mail address is not correctly set when candidate is excluded by RdP

### ISSUE THREAD

**Issue by duiliol** [consiglionazionaledellericerche/cool-jconon#36]
Upon excluding a candidate from an RdP user, after uploading the attachment, the candidate is effectively excluded. 

![image](https://user-images.githubusercontent.com/34539337/148222928-d6bb1e1c-1ed2-4e6a-8e6e-dd93cc00a70d.png)

However, the corresponding exclusion communication (Esclusioni-Visualizza) does not have a status or a mail address set:

![image](https://user-images.githubusercontent.com/34539337/148223225-a9a30636-21c9-46db-baee-90f99a204d35.png)

Additionally, looking at candidate information from "Visualizza" command shows address and telephone number from the candidate and email address of the RdP who excluded the candidate:

![image](https://user-images.githubusercontent.com/34539337/148223779-1422ecbb-f8e2-45d6-94a4-f2ede907220d.png)

**Comment by duiliol** [comment]
Solution may be similar to the one in commit 40e13331100da60ec64d7ff67f4fc923e8bd79a7 "Add state for manually upload communication and convocation" of 9/11/2021.

**Comment by mspasiano** [comment]
Available on version 4.10.6
