### ISSUE TITLE
Allow local font download instead of Google fonts

### ISSUE THREAD

**Issue by rglauco** [consiglionazionaledellericerche/cool-jconon#40]
A [recent controversial German court decision](https://rewis.io/urteile/urteil/lhm-20-01-2022-3-o-1749320/) imposed a fine for using Google CDNs, particularly on font downloads. 
Although by many this is not considered as a problem (given the territorial scope of the decision and the de-facto ubiquity of google world), it may be worth evaluate the fact that [Google figures itself as data controller](https://github.com/google/fonts/issues/1495), and in the Chrome<->"Google sites" communications it persists the use of X-client-data HTTP header (uniquely identifying the user).
It might be useful, in order to enforce data protection, to offer an option to switch to a local hosted fonts download.
https://github.com/consiglionazionaledellericerche/cool-jconon/blob/3f91eb426614473ec07dbc4ac273a888251898e5/cool-jconon-webapp-resources/src/main/resources/pages/home/main.get.head.ftl#L2

**Comment by mspasiano** [comment]
New feature is avalaible with version 5.0.15
