### ISSUE TITLE
integrazione protocollo?

### ISSUE THREAD

**Issue by hobyhop** [consiglionazionaledellericerche/cool-jconon#48]
Nel tracciato record dell'export delle domande è presente un campo relativo al protocollo della domanda.
Come è possibile valorizzarlo?
E' già presente il codice di base per l'integrazione con i sistemi di protocollo?

**Comment by mspasiano** [comment]
Nel fork utilizzato da AGID viene effettuato il protocollo della domanda tramite integrazione con servizi REST con la piattaforma gestita da Almaviva:
https://github.com/AgID/selezioni-online/blob/master/src/main/java/it/cnr/si/cool/jconon/agid/service/AGIDCallService.java#L140-L167
