### ISSUE TITLE
Informazioni sulle candidature incomplete

### ISSUE THREAD

**Issue by hobyhop** [consiglionazionaledellericerche/cool-jconon#49]
Salve.
Abbiamo una contestazione di un candidato non ammesso alle prove concorsuali.
Dall'interfaccia di amministrazione (screenshot) la sua domanda risulta in stato Provvisoria, mentre le altre sono correttamente in stato "Inviata".
Come possiamo estrarre l'informazione sullo stato e sull'attività del candidato sul bando di concorso in modo da chiarire l'episodio?
Grazie,
Mario De Chenno

**Comment by mspasiano** [comment]
Salve, lo potete fare dai log applicativi, tramite una grep del tipo: `cat /log-data/app-server/selezioni/selezioni.log|grep "application/send" ` dovreste vedere una riga `Path: POST /manage-application/send?ajax=true` con l'informazione del candidato.
