### ISSUE TITLE
Anomalia esclusione candidato

### ISSUE THREAD

**Issue by xm3ron** [consiglionazionaledellericerche/cool-jconon#52]
Quando viene caricata un'esclusione relativa ad una domanda tramite "Operazioni"-"Escludi", appare il bollino rosso "Esclusa" sotto la domanda interessata, ma la relativa Esclusione non ha alcuno stato (dovrebbe essere GENERATA). 

Per tale motivo, quando andiamo a fare l'invio, che nella nostra istanza è possibile solo per quelle in stato generata, non avviene nulla perché manca lo stato.

**Comment by mspasiano** [comment]
Quando viene caricato un provvedimento di esclusione, viene chiesto anche lo stato, coe mostrato nella figura sottostante, ed è obbligatorio, può assumere i valori "Generato", "Firmato", "Spedito", "Consegnato" 
![image](https://github.com/consiglionazionaledellericerche/cool-jconon/assets/8926256/afdb23c4-0c6a-4fab-8531-4075576bfbe1)

Forse avete sovrascitto il comportamento di base che potete trovare qui: https://github.com/consiglionazionaledellericerche/cool-jconon/blob/master/cool-jconon-webapp-resources/src/main/resources/bulkInfo/D_jconon_esclusione_attachment.xml#L18-L34
